name: Build and upload artifact

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps
        run: npm ci || npm install

      - name: Build
        run: |
          # example build - replace with your real build command
          mkdir -p dist
          echo "hello" > dist/index.html

      - name: Create dist.zip
        run: zip -r dist.zip dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-zip
          path: dist.zip
          retention-days: 7
