name: CI - simple

on:
  push:
    branches: [ main ]

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print CI start
        run: |
          echo "CI started"
