name: Secrets and Environment Variables
   
   on:
     push:
       branches: [main]
   
   env:
     APP_NAME: my-application
     ENVIRONMENT: production
   
   jobs:
     deploy:
       runs-on: ubuntu-latest
       
       steps:
         - name: Checkout code
           uses: actions/checkout@v3
         
         - name: Use environment variables
           run: |
             echo "Deploying ${{ env.APP_NAME }} to ${{ env.ENVIRONMENT }}"
             echo "Repository: ${{ github.repository }}"
         
         - name: Deploy with secret
           env:
             DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
           run: |
             # Secret is automatically masked in logs
             echo "Deploying with token..."
             echo "Token length: ${#DEPLOY_TOKEN}"
             # This will show as *** in logs
             echo "Token: $DEPLOY_TOKEN"
             echo "Deployment completed successfully!"
         
         - name: Verify secret is masked
           run: |
             echo "Secret verification complete"
             echo "Token was used securely without exposure"